# Generated by Django 4.0.1 on 2022-01-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0002_alter_employee_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Management', 'Managment'), ('Sales', 'Sales'), ('Support', 'Support')], max_length=20),
        ),
    ]
