# Generated by Django 4.0.1 on 2022-01-24 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('1', 'Prospect'), ('2', 'Customer')], max_length=10)),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True)),
                ('phone', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=25)),
                ('compagny_name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('uptaded_time', models.DateTimeField(auto_now_add=True, verbose_name='updated_time')),
                ('sales_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
