# Generated by Django 4.0.1 on 2022-01-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_compagny_name_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Prospect', 'Prospect'), ('Customer', 'Customer')], max_length=10),
        ),
    ]
