# Generated by Django 4.0.1 on 2022-01-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uptaded_time',
            field=models.DateTimeField(verbose_name='updated_time'),
        ),
    ]
