# Generated by Django 4.0.1 on 2022-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_uptaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uptaded_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated_time'),
        ),
    ]
