# Generated by Django 4.0.1 on 2022-01-26 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_uptaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='uptaded_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2022, 1, 26, 14, 36, 26, 893323, tzinfo=utc), verbose_name='updated_time'),
            preserve_default=False,
        ),
    ]
