# Generated by Django 4.0.1 on 2022-02-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_client_uptaded_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uptaded_time',
            new_name='updated_time',
        ),
    ]
