# Generated by Django 4.0.1 on 2022-01-28 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_alter_client_uptaded_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event_beginning', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Finished', 'Finished')], max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='contract_created time')),
                ('uptaded_time', models.DateTimeField(auto_now=True, verbose_name='contract_updated_time')),
                ('support_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('value', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Signed', 'Signed')], max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='contract_created time')),
                ('uptaded_time', models.DateTimeField(auto_now=True, verbose_name='contract_updated_time')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_client', to='clients.client')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_event', to='contractsEvents.event')),
                ('sales_administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_administrator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
