# Generated by Django 4.0.1 on 2022-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsEvents', '0002_alter_contract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='value',
            field=models.IntegerField(max_length=20),
        ),
    ]
