# Generated by Django 4.0.1 on 2022-02-04 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contractsEvents', '0004_alter_contract_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='support_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
