# Generated by Django 4.0.1 on 2022-02-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractsEvents', '0005_alter_event_support_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='uptaded_time',
            new_name='updated_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='uptaded_time',
            new_name='updated_time',
        ),
    ]
